#include "trust_store.h"

extern "C" {
// These symbols are generated by ESP-IDF for EMBED_TXTFILES
extern const char _binary_server_crt_start[] asm("_binary_server_crt_start");
extern const char _binary_server_crt_end[]   asm("_binary_server_crt_end");
}

namespace trust_store {

const char* server_cert_pem() {
    return _binary_server_crt_start;
}

size_t server_cert_pem_len() {
    return static_cast<size_t>(_binary_server_crt_end - _binary_server_crt_start);
}

}
